################################ GENERAL CONFIG ################################

publish_period: 0.02

max_expected_latency: 0.1   # 最大预期延迟

move_group_name: "robot_arm"   # 移动组名称

############################# INCOMING COMMAND SETTINGS ########################
pose_command_in_topic: ~/pose_target_cmds    # 末端位姿控制
cartesian_command_in_topic: ~/delta_twist_cmds #末端速度控制
joint_command_in_topic: ~/delta_joint_cmds   # 关节速度控制

command_in_type: "unitless"

scale:
  linear: 0.1
  rotational: 0.3
  joint:  0.3
incoming_command_timeout: 0.1

################################ TWIST SETTINGS #################################

apply_twist_commands_about_ee_frame: true

############################ POSE TRACKING SETTINGS #############################

pose_tracking:
  linear_tolerance: 0.001
  angular_tolerance: 0.01

############################## OUTGOING COMMAND SETTINGS #######################

status_topic: ~/status

command_out_topic: "/arm_controller/joint_trajectory"
command_out_type: "trajectory_msgs/JointTrajectory"

publish_joint_positions: true

publish_joint_velocities: true

publish_joint_accelerations: false

############################## PLANNING SCENE MONITOR ##########################

monitored_planning_scene_topic: "/planning_scene"

joint_topic: "/joint_states"
check_octomap_collisions: false

is_primary_planning_scene_monitor: true

############################### SMOOTHING PLUGIN ###############################

use_smoothing: true

smoothing_filter_plugin_name: "online_signal_smoothing::ButterworthFilterPlugin"

############################# COLLISION MONITOR ################################

check_collisions: false



############################# SINGULARITY CHECKING #############################

lower_singularity_threshold: 50.0

hard_stop_singularity_threshold: 100.0

leaving_singularity_threshold_multiplier: 2.0

singularity_step_scale: 0.1

############################### JOINT LIMITING #################################
joint_limit_margins: [0.1]

planning_frame: base_link                # MoveIt 规划参考坐标系
ee_frame_name: servo_6              # 末端执行器 link（robot_arm 组的末端）
robot_link_command_frame: base_link  # 指令参考坐标系（Twist 命令基于哪个 link）